/* ============================================================
   Noor Date Nights — data
   Date spots, restaurants and July 2026 events around the
   University of Pittsburgh (Oakland) campus.
   ============================================================ */

// Refined, muted category accents (used as a small dot + label).
const CATEGORIES = {
  dinner:   { label: "Dinner",   accent: "#8E2C48" },
  culture:  { label: "Culture",  accent: "#6B5B95" },
  outdoors: { label: "Outdoors", accent: "#4F7355" },
  movies:   { label: "Movies",   accent: "#B07A2E" },
  active:   { label: "Active",   accent: "#3E7C82" },
  views:    { label: "Views",    accent: "#A8602F" },
  event:    { label: "Event",    accent: "#9B3B5A" },
};

const DEFAULT_DATE = "2026-07-01"; // default day when adding an undated idea
const SEASON_START = "2026-06-30";
const SEASON_END = "2026-08-30";

/* ---- Evergreen date ideas (no fixed date) ---- */
const IDEAS = [
  {
    id: "phipps",
    kind: "idea",
    title: "Phipps Conservatory & Botanical Gardens",
    category: "culture",
    blurb:
      "A glowing glass palace of orchids and seasonal flower shows, free for Noor with a Pitt ID. A calm, beautiful afternoon minutes from campus.",
    where: "1 Schenley Drive, Oakland",
    transit: "~10 min walk from campus",
    link: "https://www.phipps.conservatory.org/exhibits-and-events/calendar",
    linkLabel: "Phipps calendar",
  },
  {
    id: "cathedral",
    kind: "idea",
    title: "Nationality Rooms at the Cathedral of Learning",
    category: "culture",
    blurb:
      "Tour 31 hand-built rooms hidden inside Pitt's gothic tower, each one a different country — quiet, gorgeous, and right outside your door.",
    where: "Cathedral of Learning, Pitt campus",
    transit: "On campus",
    link: "https://www.nationalityrooms.pitt.edu/",
    linkLabel: "Tour info",
  },
  {
    id: "schenley",
    kind: "idea",
    title: "Sunset walk through Schenley Park",
    category: "outdoors",
    blurb:
      "456 acres of trails, Panther Hollow lake and shady woods next to the dorms. Bring a blanket and watch the city go gold.",
    where: "Schenley Park, Oakland",
    transit: "Adjacent to campus",
    link: "https://pittsburghparks.org/parks/schenley-park/",
    linkLabel: "Park info",
  },
  {
    id: "carnegie-museums",
    kind: "idea",
    title: "Carnegie Museums of Art & Natural History",
    category: "culture",
    blurb:
      "Dinosaurs, Impressionists and the Hall of Architecture under one roof. A rainy-day-proof date you can lose a whole afternoon in.",
    where: "4400 Forbes Ave, Oakland",
    transit: "~8 min walk from campus",
    link: "https://carnegiemuseums.org/",
    linkLabel: "Museum info",
  },
  {
    id: "amc-waterfront",
    kind: "idea",
    title: "Movie night at AMC Waterfront 22",
    category: "movies",
    blurb:
      "Catch a new release at the Waterfront, then grab dessert and browse the bookshop next door. An easy, classic night out.",
    where: "The Waterfront, Homestead",
    transit: "57 / 61C bus (~25 min) or ~12 min drive",
    link: "https://www.amctheatres.com/movie-theatres/pittsburgh/amc-waterfront-22",
    linkLabel: "Showtimes",
  },
  {
    id: "mt-washington",
    kind: "idea",
    title: "Sunset at the Mount Washington overlook",
    category: "views",
    blurb:
      "The most romantic skyline view in the city. Ride up the incline, watch the three rivers light up, linger as long as you like.",
    where: "Grandview Ave, Mt. Washington",
    transit: "~12 min drive from campus",
    link: "https://www.visitpittsburgh.com/neighborhoods/mount-washington/",
    linkLabel: "Overlook info",
  },
  {
    id: "kayak",
    kind: "idea",
    title: "Kayak the three rivers",
    category: "active",
    blurb:
      "Rent a tandem kayak and paddle past the skyline. Sunny, a little silly, and surprisingly serene on a summer afternoon.",
    where: "Riverfront launches, Pittsburgh",
    transit: "~10–15 min drive from campus",
    link: "https://kayakpittsburgh.org/",
    linkLabel: "Rentals",
  },
  {
    id: "ascend",
    kind: "idea",
    title: "Bouldering at Ascend South Side",
    category: "active",
    blurb:
      "Climb the walls together at this bouldering gym with skyline views. Great for first-timers and the competitive type alike.",
    where: "Ascend, South Side",
    transit: "54 bus or ~10 min drive",
    link: "https://www.ascendclimbing.com/south-side/",
    linkLabel: "Gym info",
  },
  {
    id: "frick-park",
    kind: "idea",
    title: "Walk the woods at Frick Park",
    category: "outdoors",
    blurb:
      "Pittsburgh's wildest city park — shady ravines and miles of trails, with the Frick mansion, cafe and gardens right beside it.",
    where: "Frick Park, Point Breeze",
    transit: "~12 min drive from campus",
    link: "https://www.thefrickpittsburgh.org/",
    linkLabel: "Frick info",
  },
];

/* ---- Restaurants (dinner dates, aiming around ~$80 after tip) ---- */
const RESTAURANTS = [
  {
    id: "girasole",
    kind: "idea",
    title: "Girasole",
    category: "dinner",
    blurb:
      "Higher-end-feeling Italian — romantic and rustic without the wild pricing. Pastas run high-teens to high-20s (penne marinara $17, several pastas $27–28).",
    where: "Shadyside",
    budget: "Two pasta entrées, split a cheaper starter, skip drinks.",
    link: "https://www.girasolepgh.com/seasonal-menu",
    linkLabel: "Menu",
  },
  {
    id: "point-brugge",
    kind: "idea",
    title: "Point Brugge Cafe",
    category: "dinner",
    blurb:
      "A cozy neighborhood bistro that feels like a real date restaurant without being too formal — the kitchen leans Belgian, with mussels, flatbreads and a $19 mezze.",
    where: "Point Breeze",
    budget: "Split a starter + two lower/mid entrées, or do mussels & flatbread.",
    link: "https://www.pointbrugge.com/point-brugge-dinner-menu",
    linkLabel: "Menu",
  },
  {
    id: "butterjoint",
    kind: "idea",
    title: "Butterjoint",
    category: "dinner",
    blurb:
      "Closest to Pitt and the most elevated of the cozy spots — North Oakland food and drinks with French-bistro leanings at 208 N. Craig St.",
    where: "North Oakland · Craig Street",
    budget: "Best on happy hour: $6 appetizers and $8 classic cocktails, 4–6 PM.",
    link: "https://butterjoint.com/the-menu/",
    linkLabel: "Menu",
  },
  {
    id: "pasha",
    kind: "idea",
    title: "Pasha Cafe & Lounge",
    category: "dinner",
    blurb:
      "An elevated Mediterranean & Turkish date spot in Shadyside. Appetizers around $7.50–$8.50, salads around $14 — easy to share generously.",
    where: "Shadyside",
    budget: "Split hummus or grape leaves + two mains, skip alcohol.",
    link: "https://pashacafe.net/menu",
    linkLabel: "Menu",
  },
  {
    id: "piccolo-forno",
    kind: "idea",
    title: "Piccolo Forno",
    category: "dinner",
    blurb:
      "Warm, handmade-pasta-and-pizza Italian in Lawrenceville. It's BYOB with an $8 cork fee, so you can bring wine without the restaurant markup.",
    where: "Lawrenceville",
    budget: "Split one app + two pastas/pizzas; BYOB only if you want wine.",
    link: "https://www.piccolo-forno.com/menu/",
    linkLabel: "Menu",
  },
  {
    id: "mercurios",
    kind: "idea",
    title: "Mercurio's Shadyside",
    category: "dinner",
    blurb:
      "Casual-but-charming Neapolitan pizza, wine and house gelato on Walnut Street (5523 Walnut St). A relaxed, feel-good dinner.",
    where: "Shadyside",
    budget: "Two pizzas + gelato, or one app — easy to stay near $80.",
    link: "https://mercuriosgelatopizza.com/pittsburgh-shadyside-mercurio-s-shadyside-food-menu",
    linkLabel: "Menu",
  },
  {
    id: "senti",
    kind: "idea",
    title: "Senti",
    category: "dinner",
    blurb:
      "A more upscale Italian wine-bar in Lawrenceville — the upper edge of the budget. Starters like meatballs ($11), arancini ($13) and apps around $20–22.",
    where: "Lawrenceville",
    budget: "Two modest mains or one app + lighter plates, no drinks.",
    link: "https://www.sentirestaurant.com/senti-restaurant-menus/",
    linkLabel: "Menu",
  },
  {
    id: "union-grill",
    kind: "idea",
    title: "Union Grill",
    category: "dinner",
    blurb:
      "Less romantic but reliable and a short walk from Pitt — an old-school Oakland tradition that's a notch above fast-casual.",
    where: "Oakland · Craig Street",
    budget: "Two entrées + maybe an appetizer.",
    link: "https://www.uniongrilloakland.com/menus/",
    linkLabel: "Menu",
  },
];

/* ---- July 2026 events ---- */
const EVENTS = [
  {
    id: "phipps-wonderland", kind: "event", category: "culture",
    title: "Phipps Summer Flower Show: Alice's Adventures in Wonderland",
    dateLabel: "Any day in July", date: null,
    where: "Phipps Conservatory, 1 Schenley Drive",
    blurb: "Not free, but reasonable and very pretty — themed flower displays and photo spots right by Pitt.",
    link: "https://www.phipps.conservatory.org/exhibits-and-events/calendar", linkLabel: "Phipps calendar",
  },
  {
    id: "carnegie-international", kind: "event", category: "culture",
    title: "59th Carnegie International",
    dateLabel: "Any day in July", date: null,
    where: "Carnegie Museum of Art, 4400 Forbes Ave",
    blurb: "Artsy and calm, easy to pair with coffee or food in Oakland after. Student discounts may help.",
    link: "https://carnegiemuseums.org/events/", linkLabel: "Museum events",
  },
  {
    id: "delta", kind: "event", category: "event",
    title: "Delta (Inside Out series)",
    dateLabel: "Thu, Jul 2", date: "2026-07-02", time: "5:00 PM",
    where: "Carnegie Museum of Art Sculpture Court, 4400 Forbes Ave",
    blurb: "Free outdoor music and performance right in Oakland — a great low-pressure first date.",
    link: "https://carnegieart.org/series/inside-out/", linkLabel: "Inside Out series",
  },
  {
    id: "yoga-plaza", kind: "event", category: "active",
    title: "Yoga in Schenley Plaza",
    dateLabel: "Thu, Jul 2", date: "2026-07-02", time: "6:00–7:00 PM",
    where: "Schenley Plaza, 4100 Forbes Ave",
    blurb: "A cute, active date literally across the street from Pitt.",
    link: "https://pittsburghparks.org/events/", linkLabel: "Parks events",
  },
  {
    id: "neighborhood-flea", kind: "event", category: "event",
    title: "Neighborhood Flea — Schenley Plaza",
    dateLabel: "Sun, Jul 5", date: "2026-07-05", time: "11:00 AM–4:00 PM",
    where: "Schenley Plaza, 4100 Forbes Ave",
    blurb: "Browse vintage and handmade finds, grab food, and wander around Oakland.",
    link: "https://pittsburghparks.org/venue/schenley-plaza/", linkLabel: "Schenley Plaza",
  },
  {
    id: "northside-music", kind: "event", category: "event",
    title: "Northside Music Festival",
    dateLabel: "Fri–Sun, Jul 10–12", date: "2026-07-10",
    where: "Deutschtown / Northside",
    blurb: "Free live music, food trucks and art vendors — a very solid summer date.",
    link: "https://www.visitpittsburgh.com/blog/pittsburghs-northside-music-festival/", linkLabel: "Festival info",
  },
  {
    id: "art-summer-rhythms", kind: "event", category: "event",
    title: "Art and Summer Rhythms",
    dateLabel: "Sat, Jul 11", date: "2026-07-11", time: "12:00 PM",
    where: "Carnegie Museum of Art Sculpture Court, 4400 Forbes Ave",
    blurb: "Free daytime art, music and performance in Oakland.",
    link: "https://carnegieart.org/series/inside-out/", linkLabel: "Inside Out series",
  },
  {
    id: "hoppy-hour-11", kind: "event", category: "event",
    title: "Hoppy Hour with Rabbit Wranglers",
    dateLabel: "Sat, Jul 11", date: "2026-07-11", time: "10:30 AM–12:00 PM",
    where: "Phipps Conservatory, 1 Schenley Drive",
    blurb: "One of the cutest options — rabbits plus the Phipps flower show. Reasonably priced for what it is.",
    link: "https://www.phipps.conservatory.org/exhibits-and-events/calendar", linkLabel: "Phipps calendar",
  },
  {
    id: "walnut-car-show", kind: "event", category: "event",
    title: "Walnut Street Invitational Car Show",
    dateLabel: "Mon, Jul 13", date: "2026-07-13", time: "5:00–9:00 PM",
    where: "Walnut Street, Shadyside",
    blurb: "A walk-around date in Shadyside with an easy dessert, coffee or dinner add-on.",
    link: "https://pvgp.org/events/schenley-park-race-weekend/", linkLabel: "Event info",
  },
  {
    id: "tune-up", kind: "event", category: "event",
    title: "Tune-Up @ SouthSide Works",
    dateLabel: "Wed, Jul 15", date: "2026-07-15", time: "6:00–9:00 PM",
    where: "SouthSide Works",
    blurb: "An outdoor evening event with plenty of food options nearby.",
    link: "https://pvgp.org/events/schenley-park-race-weekend/", linkLabel: "Event info",
  },
  {
    id: "osmosis", kind: "event", category: "event",
    title: "Osmosis (Inside Out series)",
    dateLabel: "Thu, Jul 16", date: "2026-07-16", time: "5:00 PM",
    where: "Carnegie Museum of Art Sculpture Court, 4400 Forbes Ave",
    blurb: "Free Oakland music and performance — easy to fold into dinner after.",
    link: "https://carnegieart.org/series/inside-out/", linkLabel: "Inside Out series",
  },
  {
    id: "picklesburgh", kind: "event", category: "event",
    title: "Picklesburgh 2026",
    dateLabel: "Thu–Sun, Jul 16–19", date: "2026-07-16",
    where: "Downtown — Sister Bridges, Market Square & PPG Plaza",
    blurb: "Free admission, funny, memorable and very Pittsburgh.",
    link: "https://www.picklesburgh.com/", linkLabel: "Picklesburgh",
  },
  {
    id: "vintage-grand-prix", kind: "event", category: "event",
    title: "Pittsburgh Vintage Grand Prix Race Weekend",
    dateLabel: "Sat–Sun, Jul 18–19", date: "2026-07-18", time: "9:30 AM–5:00 PM",
    where: "Schenley Park, Schenley Dr & Darlington Rd",
    blurb: "A huge Schenley event with vintage cars, food and vendors — super convenient from Pitt.",
    link: "https://pvgp.org/events/schenley-park-race-weekend/", linkLabel: "Race weekend",
  },
  {
    id: "cinema-phoenician", kind: "event", category: "movies",
    title: "Cinema in the Park: The Phoenician Scheme",
    dateLabel: "Wed, Jul 22", date: "2026-07-22", time: "Sunset",
    where: "Schenley Plaza",
    blurb: "A free outdoor movie date right next to Pitt — bring a blanket.",
    link: "https://www.pittsburghpa.gov/Recreation-Events/Events/Dollar-Bank-Cinema-In-The-Park/Schenley-Plaza", linkLabel: "Cinema in the Park",
  },
  {
    id: "jazz-garden", kind: "event", category: "event",
    title: "Jazz in the Garden",
    dateLabel: "Thu, Jul 23", date: "2026-07-23", time: "6:30–9:00 PM",
    where: "Phipps Conservatory, 1 Schenley Drive",
    blurb: "A romantic evening option — worth it if the ticket price fits your budget.",
    link: "https://www.phipps.conservatory.org/", linkLabel: "Phipps",
  },
  {
    id: "adios-agave", kind: "event", category: "event",
    title: "Adiós Agave Night at Phipps",
    dateLabel: "Fri, Jul 24", date: "2026-07-24", time: "5:00–10:00 PM",
    where: "Phipps Conservatory, 1 Schenley Drive",
    blurb: "An evening garden event — keep it if the ticket price is reasonable.",
    link: "https://www.phipps.conservatory.org/", linkLabel: "Phipps",
  },
  {
    id: "yoga-garden", kind: "event", category: "active",
    title: "Yoga in the Garden",
    dateLabel: "Sat, Jul 25", date: "2026-07-25", time: "9:00–10:00 AM",
    where: "Phipps Conservatory, 1 Schenley Drive",
    blurb: "A calm morning date, likely cheaper than the formal Phipps evening events.",
    link: "https://www.phipps.conservatory.org/exhibits-and-events/calendar", linkLabel: "Phipps calendar",
  },
  {
    id: "hoppy-hour-25", kind: "event", category: "event",
    title: "Hoppy Hour with Rabbit Wranglers",
    dateLabel: "Sat, Jul 25", date: "2026-07-25", time: "10:30 AM–12:00 PM",
    where: "Phipps Conservatory, 1 Schenley Drive",
    blurb: "Another very cute Phipps-and-rabbits option if you miss the first one.",
    link: "https://www.phipps.conservatory.org/exhibits-and-events/calendar", linkLabel: "Phipps calendar",
  },
  {
    id: "mary-schenley-day", kind: "event", category: "event",
    title: "Mary Schenley Day / Family Day",
    dateLabel: "Sat, Jul 25", date: "2026-07-25", time: "11:00 AM–6:00 PM",
    where: "Schenley Plaza",
    blurb: "Free carousel rides, music and activities — a very easy Oakland date.",
    link: "https://pittsburghparks.org/family-days/", linkLabel: "Family days",
  },
  {
    id: "launching-peace", kind: "event", category: "event",
    title: "Launching Peace (Inside Out series)",
    dateLabel: "Sat, Jul 25", date: "2026-07-25", time: "12:00 PM",
    where: "Carnegie Museum of Art Sculpture Court, 4400 Forbes Ave",
    blurb: "A free, artsy daytime date near Pitt.",
    link: "https://carnegieart.org/series/inside-out/", linkLabel: "Inside Out series",
  },
  {
    id: "openstreets", kind: "event", category: "active",
    title: "OpenStreetsPGH",
    dateLabel: "Sun, Jul 26", date: "2026-07-26", time: "10:00 AM–2:00 PM",
    where: "Strip District + Lawrenceville",
    blurb: "Walk, bike or scooter the car-free streets, grab coffee and food, and let it feel spontaneous.",
    link: "https://bikepgh.org/2026/05/18/just-announced-openstreetspgh-returns-for-2026/", linkLabel: "OpenStreets info",
  },
  {
    id: "cinema-reelabilities", kind: "event", category: "movies",
    title: "Cinema in the Park: ReelAbilities Summer Shorts",
    dateLabel: "Sun, Jul 26", date: "2026-07-26", time: "Sunset",
    where: "Schenley Plaza",
    blurb: "A free outdoor movie night with a more unique short-film format.",
    link: "https://www.pittsburghpa.gov/Recreation-Events/Events/Dollar-Bank-Cinema-In-The-Park/Schenley-Plaza", linkLabel: "Cinema in the Park",
  },
  {
    id: "cinema-badlands", kind: "event", category: "movies",
    title: "Cinema in the Park: Badlands (1973)",
    dateLabel: "Wed, Jul 29", date: "2026-07-29", time: "Sunset",
    where: "Schenley Plaza",
    blurb: "A classic outdoor movie date right near campus.",
    link: "https://www.pittsburghpa.gov/Recreation-Events/Events/Dollar-Bank-Cinema-In-The-Park/Schenley-Plaza", linkLabel: "Cinema in the Park",
  },
  {
    id: "cusp", kind: "event", category: "event",
    title: "Cusp (Inside Out series)",
    dateLabel: "Thu, Jul 30", date: "2026-07-30", time: "5:00 PM",
    where: "Carnegie Museum of Art Sculpture Court, 4400 Forbes Ave",
    blurb: "Free outdoor music and performance in Oakland.",
    link: "https://carnegieart.org/series/inside-out/", linkLabel: "Inside Out series",
  },
  {
    id: "hprizm", kind: "event", category: "culture",
    title: "Hprizm: Sound of the City (opening)",
    dateLabel: "Fri, Jul 31", date: "2026-07-31",
    where: "Wood Street Galleries, Downtown",
    blurb: "A gallery opening downtown — a quieter, artsy date-night option.",
    link: "https://trustarts.org/calendar", linkLabel: "Trust calendar",
  },
];
